-- AlterTable
ALTER TABLE `vehicles`
  MODIFY `status` ENUM(
    'ACTIVE',
    'IN_MAINTENANCE',
    'OUT_OF_SERVICE',
    'RESERVED',
    'DECOMMISSIONED',
    'PENDING_VERIFICATION',
    'PENDING_REPLACEMENT'
  ) NOT NULL DEFAULT 'ACTIVE';
