/**
 * Run with: node src/utils/generateFrontendPermissions.js
 * Outputs a JS module matching dashboard/src/utils/rolePermissions.js
 */
const { PERMISSIONS, ROLE_PERMISSIONS } = require('../constants/permissions');

const ROLE_LABELS = {
  SUPER_ADMIN: { labelAr: 'مدير عام', labelEn: 'Super Admin' },
  OPERATIONS_ADMIN: { labelAr: 'مدير عمليات', labelEn: 'Operations Admin' },
  HR_ADMIN: { labelAr: 'مدير موارد بشرية', labelEn: 'HR Admin' },
  FLEET_ADMIN: { labelAr: 'مدير أسطول', labelEn: 'Fleet Admin' },
  FINANCE_ADMIN: { labelAr: 'مدير مالي', labelEn: 'Finance Admin' },
  SUPERVISOR: { labelAr: 'مشرف', labelEn: 'Supervisor' },
  DRIVER: { labelAr: 'سائق', labelEn: 'Driver' },
};

function toJsMap(obj, indent = 2) {
  const pad = ' '.repeat(indent);
  const entries = Object.entries(obj).map(([k, v]) => {
    if (Array.isArray(v)) {
      const items = v.map((s) => `PERMISSIONS.${Object.keys(PERMISSIONS).find((pk) => PERMISSIONS[pk] === s) || `'${s}'`}`).join(',\n${pad}  ');
      return `${pad}${k}: [\n${pad}  ${items}\n${pad}]`;
    }
    return `${pad}${k}: ${JSON.stringify(v)}`;
  });
  return `{\n${entries.join(',\n')}\n${' '.repeat(indent - 2)}}`;
}

const out = [
  '// AUTO-GENERATED by src/utils/generateFrontendPermissions.js — DO NOT EDIT MANUALLY',
  "export const PERMISSIONS = Object.freeze({",
  ...Object.entries(PERMISSIONS).map(([k, v]) => `  ${k}: '${v}',`),
  '});',
  '',
  'export const DASHBOARD_VIEW_PERMISSIONS = [',
  `  PERMISSIONS.USERS_READ,`,
  `  PERMISSIONS.FLEET_READ,`,
  `  PERMISSIONS.HR_READ,`,
  `  PERMISSIONS.FINANCE_READ,`,
  `  PERMISSIONS.COMPLIANCE_READ,`,
  '];',
  '',
  'const ALL = Object.values(PERMISSIONS);',
  '',
  'export const ROLE_PERMISSIONS = {',
  ...Object.entries(ROLE_PERMISSIONS).map(([role, perms]) => {
    const permStrs = perms.length
      ? perms.map((p) => {
          const pk = Object.keys(PERMISSIONS).find((k) => PERMISSIONS[k] === p);
          return `    PERMISSIONS.${pk}`;
        }).join(',\n')
      : '';
    return `  ${role}: [\n${permStrs}\n  ]`;
  }),
  '};',
  '',
  'export function getGrantedPermissions(role) {',
  "  if (!role) return new Set();",
  "  if (role === 'SUPER_ADMIN') return new Set(ALL);",
  '  return new Set(ROLE_PERMISSIONS[role] || []);',
  '}',
  '',
  'export function hasAnyPermission(role, permissionList) {',
  '  if (!permissionList?.length) return true;',
  '  const g = getGrantedPermissions(role);',
  '  return permissionList.some((p) => g.has(p));',
  '}',
  '',
  'export function canSeeNavItem(role, permissionList, options = {}) {',
  "  if (options.superAdminOnly) return role === 'SUPER_ADMIN';",
  '  return hasAnyPermission(role, permissionList);',
  '}',
].join('\n');

console.log(out);
