const statusMap = {
  ACTIVE: { label: 'نشط', className: 'badge-success' },
  TEMPORARILY_SUSPENDED: { label: 'موقف مؤقتاً', className: 'badge-danger' },
  RESTRICTED: { label: 'مقيّد', className: 'badge-warning' },
  UNDER_INVESTIGATION: { label: 'تحت التحقيق', className: 'badge-warning' },
  PENDING_APPROVAL: { label: 'بانتظار الموافقة', className: 'badge-info' },
  INCOMPLETE_PROFILE: { label: 'ملف غير مكتمل', className: 'badge-neutral' },
  ARCHIVED: { label: 'مؤرشف', className: 'badge-neutral' },
  REQUESTED: { label: 'مطلوب', className: 'badge-info' },
  APPROVED: { label: 'مقبول', className: 'badge-success' },
  REJECTED: { label: 'مرفوض', className: 'badge-danger' },
  ENDED: { label: 'منتهي', className: 'badge-neutral' },
  CANCELLED: { label: 'ملغي', className: 'badge-neutral' },
  PENDING: { label: 'معلق', className: 'badge-info' },
  SUBMITTED: { label: 'مقدم', className: 'badge-info' },
  UNDER_REVIEW: { label: 'قيد المراجعة', className: 'badge-warning' },
  NEEDS_REVISION: { label: 'يحتاج تعديل', className: 'badge-warning' },
  VALID: { label: 'صالح', className: 'badge-success' },
  NEAR_EXPIRY: { label: 'قارب الانتهاء', className: 'badge-warning' },
  EXPIRED: { label: 'منتهي', className: 'badge-danger' },
  VERIFIED: { label: 'موثق', className: 'badge-success' },
  OPEN: { label: 'مفتوح', className: 'badge-info' },
  IN_PROGRESS: { label: 'قيد التنفيذ', className: 'badge-warning' },
  ESCALATED: { label: 'مصعّد', className: 'badge-danger' },
  RESOLVED: { label: 'تم الحل', className: 'badge-success' },
  CLOSED: { label: 'مغلق', className: 'badge-neutral' },
  REPORTED: { label: 'مبلغ عنه', className: 'badge-info' },
  CONFIRMED: { label: 'مؤكد', className: 'badge-danger' },
  DISMISSED: { label: 'مرفوض', className: 'badge-neutral' },
  PENALIZED: { label: 'معاقب', className: 'badge-danger' },
  FLAGGED: { label: 'مشبوه', className: 'badge-warning' },
  APPLIED: { label: 'مطبق', className: 'badge-success' },
  APPEALED: { label: 'معترض', className: 'badge-warning' },
  COMPLETED: { label: 'مكتمل', className: 'badge-success' },
  PENDING_RESPONSE: { label: 'بانتظار الرد', className: 'badge-info' },
  PENDING_VERIFICATION: { label: 'بانتظار التحقق', className: 'badge-info' },
  INACTIVE: { label: 'غير نشط', className: 'badge-neutral' },
  SUSPENDED: { label: 'موقف', className: 'badge-danger' },
  IN_MAINTENANCE: { label: 'في الصيانة', className: 'badge-warning' },
  OUT_OF_SERVICE: { label: 'خارج الخدمة', className: 'badge-danger' },
  DECOMMISSIONED: { label: 'خارج العمل', className: 'badge-neutral' },
  LOW: { label: 'منخفض', className: 'badge-success' },
  MEDIUM: { label: 'متوسط', className: 'badge-warning' },
  HIGH: { label: 'عالي', className: 'badge-danger' },
  CRITICAL: { label: 'حرج', className: 'badge-danger' },
  URGENT: { label: 'عاجل', className: 'badge-danger' },
};

export default function StatusBadge({ status }) {
  const config = statusMap[status] || { label: status, className: 'badge-neutral' };
  return <span className={`badge ${config.className}`}>{config.label}</span>;
}
