/**
 * Permission keys for fine-grained admin access (expand per module).
 * SUPER_ADMIN bypasses checks in requirePermission().
 */
const PERMISSIONS = {
  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  FLEET_READ: 'fleet:read',
  FLEET_WRITE: 'fleet:write',
  DOCUMENTS_READ: 'documents:read',
  DOCUMENTS_REVIEW: 'documents:review',
  SHIFTS_READ: 'shifts:read',
  SHIFTS_APPROVE: 'shifts:approve',
  HR_READ: 'hr:read',
  HR_APPROVE: 'hr:approve',
  FINANCE_READ: 'finance:read',
  FINANCE_APPROVE: 'finance:approve',
  SETTINGS_READ: 'settings:read',
  SETTINGS_WRITE: 'settings:write',
  AUDIT_READ: 'audit:read',
  COMPLIANCE_READ: 'compliance:read',
  COMPLIANCE_WRITE: 'compliance:write',
};

/** Default permissions per dashboard role */
const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  OPERATIONS_ADMIN: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.FLEET_READ,
    PERMISSIONS.FLEET_WRITE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_REVIEW,
    PERMISSIONS.SHIFTS_READ,
    PERMISSIONS.SHIFTS_APPROVE,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.COMPLIANCE_WRITE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_APPROVE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.AUDIT_READ,
  ],
  HR_ADMIN: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_REVIEW,
    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_APPROVE,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  FLEET_ADMIN: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.FLEET_READ,
    PERMISSIONS.FLEET_WRITE,
    PERMISSIONS.SHIFTS_READ,
    PERMISSIONS.SHIFTS_APPROVE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.COMPLIANCE_READ,
  ],
  FINANCE_ADMIN: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.HR_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  SUPERVISOR: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.SHIFTS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.COMPLIANCE_READ,
  ],
  DRIVER: [],
};

/** Any of these allows dashboard KPI / analytics-style read endpoints */
const DASHBOARD_VIEW_PERMISSIONS = [
  PERMISSIONS.USERS_READ,
  PERMISSIONS.FLEET_READ,
  PERMISSIONS.HR_READ,
  PERMISSIONS.FINANCE_READ,
  PERMISSIONS.COMPLIANCE_READ,
];

module.exports = { PERMISSIONS, ROLE_PERMISSIONS, DASHBOARD_VIEW_PERMISSIONS };
